graph [
	node [ id 0 label "C" ]
	node [ id 1 label "C" ]
	node [ id 2 label "O" ]
	node [ id 3 label "P" ]
	node [ id 4 label "O" ]
	node [ id 5 label "O" ]
	node [ id 6 label "O" ]
	node [ id 7 label "C" ]
	node [ id 8 label "C" ]
	node [ id 9 label "C" ]
	node [ id 10 label "C" ]
	node [ id 11 label "O" ]
	node [ id 12 label "P" ]
	node [ id 13 label "O" ]
	node [ id 14 label "O" ]
	node [ id 15 label "O" ]
	node [ id 16 label "O" ]
	node [ id 17 label "O" ]
	node [ id 18 label "O" ]
	node [ id 19 label "O" ]
	node [ id 20 label "H" ]
	node [ id 21 label "H" ]
	node [ id 22 label "H" ]
	node [ id 23 label "H" ]
	node [ id 24 label "H" ]
	node [ id 25 label "H" ]
	node [ id 26 label "H" ]
	node [ id 27 label "H" ]
	node [ id 28 label "H" ]
	node [ id 29 label "H" ]
	node [ id 30 label "H" ]
	node [ id 31 label "H" ]
	node [ id 32 label "H" ]
	node [ id 33 label "H" ]
	edge [ source 1 target 0 label "-" ]
	edge [ source 2 target 1 label "-" ]
	edge [ source 4 target 3 label "-" ]
	edge [ source 5 target 3 label "-" ]
	edge [ source 3 target 2 label "-" ]
	edge [ source 6 target 3 label "=" ]
	edge [ source 10 target 9 label "-" ]
	edge [ source 11 target 10 label "-" ]
	edge [ source 13 target 12 label "-" ]
	edge [ source 14 target 12 label "-" ]
	edge [ source 12 target 11 label "-" ]
	edge [ source 15 target 12 label "=" ]
	edge [ source 9 target 8 label "-" ]
	edge [ source 16 target 9 label "-" ]
	edge [ source 8 target 7 label "-" ]
	edge [ source 17 target 8 label "-" ]
	edge [ source 7 target 0 label "-" ]
	edge [ source 18 target 7 label "-" ]
	edge [ source 19 target 0 label "=" ]
	edge [ source 20 target 1 label "-" ]
	edge [ source 21 target 1 label "-" ]
	edge [ source 22 target 4 label "-" ]
	edge [ source 23 target 5 label "-" ]
	edge [ source 24 target 7 label "-" ]
	edge [ source 25 target 8 label "-" ]
	edge [ source 26 target 9 label "-" ]
	edge [ source 27 target 10 label "-" ]
	edge [ source 28 target 10 label "-" ]
	edge [ source 29 target 13 label "-" ]
	edge [ source 30 target 14 label "-" ]
	edge [ source 31 target 16 label "-" ]
	edge [ source 32 target 17 label "-" ]
	edge [ source 33 target 18 label "-" ]
]
