graph [
	node [ id 0 label "C" ]
	node [ id 1 label "C" ]
	node [ id 2 label "C" ]
	node [ id 3 label "O" ]
	node [ id 4 label "P" ]
	node [ id 5 label "O" ]
	node [ id 6 label "O" ]
	node [ id 7 label "O" ]
	node [ id 8 label "O" ]
	node [ id 9 label "O" ]
	node [ id 10 label "H" ]
	node [ id 11 label "H" ]
	node [ id 12 label "H" ]
	node [ id 13 label "H" ]
	node [ id 14 label "H" ]
	node [ id 15 label "H" ]
	node [ id 16 label "H" ]
	edge [ source 2 target 1 label "-" ]
	edge [ source 3 target 2 label "-" ]
	edge [ source 5 target 4 label "-" ]
	edge [ source 6 target 4 label "-" ]
	edge [ source 4 target 3 label "-" ]
	edge [ source 7 target 4 label "=" ]
	edge [ source 1 target 0 label "-" ]
	edge [ source 8 target 1 label "-" ]
	edge [ source 9 target 0 label "=" ]
	edge [ source 10 target 0 label "-" ]
	edge [ source 11 target 1 label "-" ]
	edge [ source 12 target 2 label "-" ]
	edge [ source 13 target 2 label "-" ]
	edge [ source 14 target 5 label "-" ]
	edge [ source 15 target 6 label "-" ]
	edge [ source 16 target 8 label "-" ]
]
