graph [
	node [ id 0 label "O" ]
	node [ id 1 label "P" ]
	node [ id 2 label "O" ]
	node [ id 3 label "O" ]
	node [ id 4 label "O" ]
	node [ id 5 label "H" ]
	node [ id 6 label "H" ]
	node [ id 7 label "H" ]
	edge [ source 2 target 1 label "-" ]
	edge [ source 3 target 1 label "-" ]
	edge [ source 1 target 0 label "=" ]
	edge [ source 4 target 1 label "-" ]
	edge [ source 5 target 2 label "-" ]
	edge [ source 6 target 3 label "-" ]
	edge [ source 7 target 4 label "-" ]
]
